In [10]:
import numpy as np

[[ 2.  2.  3.]
 [ 2.  4.  7.]
 [ 3.  7. 14.]]


In [ ]:
import numpy as np

a = np.zeros((3, 3), dtype=int)

v1 = int(input("Enter 1st value: "))
v2 = int(input("Enter 2nd value: "))
v3 = int(input("Enter 3rd value: "))

a[0][0] = v1
a[0][1] = a[1][0] = v2
a[0][2] = a[2][0] = v3


a[1][1] = 2 * v2
a[1][2] = a[2][1] = a[1][1] + v3
a[2][2] = a[1][2] + a[2][1]

print(a)

[[ 2  3  4]
 [ 3  6 10]
 [ 4 10 20]]


{'Name': ['Arham', 'Ameen', 'Ammar'], 'profession': ['development', 'designer', 'marketing'], 'city': ['hyd', 'karachi', 'Lahore']}


,Name,profession,city
0,Arham,development,hyd
1,Ameen,designer,karachi
2,Ammar,marketing,Lahore
